import React, { useState } from 'react';
import {
  Bell,
  AlertTriangle,
  AlertCircle,
  Info,
  CheckCircle2,
  Filter,
  Check,
  RotateCcw,
} from 'lucide-react';
import { FarmAlert, AlertSeverity, AlertStatus } from '../types';

interface AlertsViewProps {
  alerts: FarmAlert[];
  onAcknowledge: (id: string) => void;
  onResolve: (id: string) => void;
}

export const AlertsView: React.FC<AlertsViewProps> = ({
  alerts,
  onAcknowledge,
  onResolve,
}) => {
  const [statusFilter, setStatusFilter] = useState<'ALL' | AlertStatus>('ALL');
  const [severityFilter, setSeverityFilter] = useState<'ALL' | AlertSeverity>('ALL');

  const filteredAlerts = alerts.filter((a) => {
    if (statusFilter !== 'ALL' && a.status !== statusFilter) return false;
    if (severityFilter !== 'ALL' && a.severity !== severityFilter) return false;
    return true;
  });

  return (
    <div id="alerts-view" className="space-y-6">
      {/* Header & Filter Controls */}
      <div className="flex flex-col justify-between gap-4 rounded-xl border border-stone-200 bg-white p-5 shadow-xs sm:flex-row sm:items-center">
        <div>
          <div className="flex items-center space-x-2">
            <Bell className="h-5 w-5 text-emerald-800" />
            <h2 className="text-lg font-bold text-stone-900">
              Farm Alerts & Environmental Anomaly Registry
            </h2>
          </div>
          <p className="text-xs text-stone-500">
            Real-time notifications generated by deterministic sensor thresholding and agent anomaly rules.
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <div className="flex items-center space-x-1 rounded-lg border border-stone-200 bg-stone-50 p-1">
            <span className="px-1 text-[11px] font-semibold text-stone-600">Status:</span>
            {(['ALL', 'ACTIVE', 'ACKNOWLEDGED', 'RESOLVED'] as const).map((st) => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`rounded px-2 py-0.5 text-[10px] font-bold ${
                  statusFilter === st
                    ? 'bg-emerald-800 text-white'
                    : 'text-stone-600 hover:bg-stone-200'
                }`}
              >
                {st}
              </button>
            ))}
          </div>

          <div className="flex items-center space-x-1 rounded-lg border border-stone-200 bg-stone-50 p-1">
            <span className="px-1 text-[11px] font-semibold text-stone-600">Severity:</span>
            {(['ALL', 'CRITICAL', 'WARNING', 'INFO'] as const).map((sv) => (
              <button
                key={sv}
                onClick={() => setSeverityFilter(sv)}
                className={`rounded px-2 py-0.5 text-[10px] font-bold ${
                  severityFilter === sv
                    ? 'bg-stone-900 text-white'
                    : 'text-stone-600 hover:bg-stone-200'
                }`}
              >
                {sv}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="flex h-48 flex-col items-center justify-center rounded-xl border border-stone-200 bg-white p-6 text-center text-xs text-stone-400 shadow-xs">
            <CheckCircle2 className="h-8 w-8 text-emerald-600" />
            <p className="mt-2 font-medium text-stone-700">No alerts match your filter criteria.</p>
            <p className="text-[11px] text-stone-400">All environmental parameters are within safe bounds.</p>
          </div>
        ) : (
          filteredAlerts.map((alert) => (
            <div
              key={alert.id}
              className={`rounded-xl border p-4 shadow-xs transition-shadow hover:shadow-sm ${
                alert.status === 'RESOLVED'
                  ? 'border-stone-200 bg-stone-50/60 opacity-75'
                  : alert.severity === 'CRITICAL'
                  ? 'border-rose-300 bg-rose-50/30'
                  : alert.severity === 'WARNING'
                  ? 'border-amber-300 bg-amber-50/30'
                  : 'border-blue-200 bg-blue-50/20'
              }`}
            >
              <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start">
                <div className="flex items-start space-x-3">
                  <div className="mt-0.5">
                    {alert.severity === 'CRITICAL' ? (
                      <AlertTriangle className="h-5 w-5 text-rose-600" />
                    ) : alert.severity === 'WARNING' ? (
                      <AlertCircle className="h-5 w-5 text-amber-600" />
                    ) : (
                      <Info className="h-5 w-5 text-blue-600" />
                    )}
                  </div>
                  <div>
                    <div className="flex items-center space-x-2">
                      <h4 className="font-bold text-stone-900 text-sm">{alert.title}</h4>
                      <span
                        className={`rounded px-1.5 py-0.2 text-[10px] font-bold ${
                          alert.severity === 'CRITICAL'
                            ? 'bg-rose-100 text-rose-800'
                            : alert.severity === 'WARNING'
                            ? 'bg-amber-100 text-amber-800'
                            : 'bg-blue-100 text-blue-800'
                        }`}
                      >
                        {alert.severity}
                      </span>
                      <span className="rounded bg-stone-100 px-1.5 py-0.2 text-[10px] font-mono text-stone-600">
                        {alert.plotName}
                      </span>
                    </div>

                    <p className="mt-1 text-xs text-stone-700 leading-relaxed">{alert.message}</p>

                    <div className="mt-2 flex items-center space-x-4 text-[11px] text-stone-500">
                      <span>
                        Detected:{' '}
                        {new Date(alert.timestamp).toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit',
                          second: '2-digit',
                        })}
                      </span>
                      <span>Category: {alert.category}</span>
                      <span>Status: {alert.status}</span>
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center space-x-2 self-end sm:self-center">
                  {alert.status === 'ACTIVE' && (
                    <button
                      onClick={() => onAcknowledge(alert.id)}
                      className="rounded-md border border-stone-300 bg-white px-2.5 py-1 text-xs font-medium text-stone-700 hover:bg-stone-50 shadow-2xs"
                    >
                      Acknowledge
                    </button>
                  )}
                  {alert.status !== 'RESOLVED' && (
                    <button
                      onClick={() => onResolve(alert.id)}
                      className="flex items-center space-x-1 rounded-md bg-emerald-800 px-3 py-1 text-xs font-medium text-white hover:bg-emerald-700 shadow-2xs"
                    >
                      <Check className="h-3 w-3" />
                      <span>Resolve</span>
                    </button>
                  )}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
